language: python
python:
  - "3.5.2"
# command to install dependencies
services:
  - postgresql
install: 
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE DATABASE stack;" -U postgres
  - psql -c "CREATE USER stack WITH PASSWORD 'stack';" -U postgres
# command to run tests
script: 
  - py.test --cov=app -v
after_success:
  - coveralls
