language: python
python:
  - "3.5.2"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: 
  - py.test --cov=app
after_success:
  - coveralls
