FORMAT: 1A
HOST: https://stackoverflow-paul.herokuapp.com/api/v1

# Stack overflow lite

Polls is a simple API allowing consumers to view polls and vote in them.

## Sign up Collection [/auth/signup]

### Signup [POST]

Sign's in a new user

+ Request (application/json)

        {
            "username": "Paul",
            "email": "pkinuthia10@gmail.com",
            "password": "12345"
        }

+ Response 201 (application/json)

    + Headers

    + Body

            {
                "auth_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzQ2OTE4OTksImlhdCI6MTUzNDYwNTQ2OSwic3ViIjpudWxsfQ.dYtvvpJDFdYanDtnFzOPMNtMv-D5hXiiEWRQgSykF9o",
                "id": null,
                "message": "Successfully registered.",
                "status": "success"
            }
   
## Login Collection [/auth/login]

### Login [POST]

You can login and get authorization Token

+ Request (application/json)

        {
            "email": "pkinuthia10@gmail.com",
            "password": "12345"
        }

+ Response 201 (application/json)

    + Headers

    + Body

            {
              "auth_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzQ3MDkyMzksImlhdCI6MTUzNDYyMjgwOSwic3ViIjoyfQ.Wc23q6AN3XoeRr_JXX8yRqUvQ3vwObzyVIyIvXJxI8o",
              "id": 2,
              "message": "Successfully logged in.",
              "status": "success"
            }
   

## Questions Collection [/questions/]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "title": "Favourite programming language?",
            "body": "Hello Favourite programming language?"
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }